M48
; DRILL file KiCad 10.0.1 date 2026-09-20T14:17:00
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-20T14:17:00+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X2.6469Y-4.802
X2.8744Y-4.802
T2
X6.305Y-4.29
T3
X6.08Y-4.295
T4
X5.7918Y-4.3118
M30
